name = "search"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2025-03-20"

account_id = "ea4050075340f70ec8320cf50b47260c"

[env.staging]
name = "search-staging"
workers_dev = true

[env.production]
name = "search"

[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
